Cat99/config/routes.rb
Rails.application.routes.draw do
  resources :cats do 
    resources :cat_rental_requests, only:[:index]
  end
  
  resources :cat_rental_requests, only: [:new, :create]
end

Cat99/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Cat99/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint(8)        not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ApplicationRecord
  COLORS = %w(Black White Yellow Brown Orange Grey)
  validates :color, inclusion: { in: COLORS }, presence: true
  validates :sex, inclusion: { in: %w(M F) }, presence: true 
  validates :name, :description, :birth_date, presence: true 
  
  has_many :cat_rental_requests,
  primary_key: :id,
  foreign_key: :cat_id,
  class_name: :CatRentalRequest,
  dependent: :destroy 
end

Cat99/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :bigint(8)        not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CatRentalRequest < ApplicationRecord
  validates :cat_id, :start_date, :end_date, presence: true 
  validates :status, inclusion: { in: %w(PENDING APPROVED DENIED) }
  validate :does_not_overlap_approved_request
  
  belongs_to :cat,
  primary_key: :id,
  foreign_key: :cat_id,
  class_name: :Cat 
  
  def overlapping_requests
    CatRentalRequest.all
    .where(cat_id: self[:cat_id])
    .where("(start_date BETWEEN :start_date AND :end_date) OR (end_date BETWEEN :start_date AND :end_date)",
     {start_date: self[:start_date], end_date: self[:end_date]})
    
  end
  
  def overlapping_approved_requests
    overlapping_requests.where(status: 'APPROVED')
  end
  
  def does_not_overlap_approved_request
    if overlapping_approved_requests.exists?
      self.errors[:start_date] << 'Another overlapping request exists'
    end
  end
end

Cat99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

Cat99/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def new
    @cats = Cat.all
    @request = CatRentalRequest.new
    render :new
  end
end

Cat99/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all 
    render :index
  end
  
  def show
    @cat = Cat.find(params[:id])
    render :show
  end
  
  def new
    @cat = Cat.new
    render :new
  end
  
  def create
    @cat = Cat.new(cat_params)
    
    if @cat.save
      redirect_to cat_url(@cat)
    else 
      render json: @cat.errors.full_messages, status: :unprocessable_entity
    end
  end
  
  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end
  
  def update
    @cat = Cat.find(params[:id])
    
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages, status: :unprocessable_entity
    end
  end
  
  
  def destroy
  end
  
  private
  def cat_params
    params.require(:cat).permit(:name, :birth_date, :color, :sex, :description)
  end
end

Cat99/app/helpers/application_helper.rb
module ApplicationHelper
end

Cat99/app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

Cat99/app/helpers/cats_helper.rb
module CatsHelper
end

Cat99/app/views/cat_rental_requests/new.html.erb
<h1> Rent a cat! </h1>
<form class="" action=" <%= cat_rental_requests_url %>" method="post">
  
  <label for="cat_id"></label>
  <select id = "cat_id" name="cat_rental_request[cat_id]">
      <option disabled selected>--Select Cat--</option>
    
    <% @cats.each do |cat| %>
      <option value=" <%= cat.id %>"> <%= cat.name %></option>
    <% end %>
  </select>
  
  <br>
  <label for="start_date">Start Date</label>
  <input id = "start_date" type="date" name="cat_rental_request[start_date]">
  
  <br>
  <label for="end_date">End Date</label>
  <input id = "end_date" type="date" name="cat_rental_request[end_date]">
</form>

Cat99/app/views/cats/_cat_template.html.erb
<ul>
  <li> <%= cat.name %> </li>
  <li> <%= cat.birth_date %></li>
  <li> <%= cat.color%></li>
  <li> <%= cat.sex %> </li>
  <li> <%= cat.description %></li>
  <% if action == :index %>
    <li> <a href= '<%= cat_url(cat) %>'> Show Cat</a></li>
  <% else %>
    <li> <a href= '<%= cats_url %>'> Show All Cats</a></li>
  <% end %>
</ul> 

Cat99/app/views/cats/_forms.html.erb
<% if action == :edit %>
  <% final_url = cat_url(cat) %>
  <% final_str = 'Edit Cat' %>
<% else %>
  <% final_url = cats_url %>
  <% final_str = 'Create New Cat' %>
<% end %>




<form action="<%= final_url %>" method="post">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  
  <label for="name">Name</label>
  <input id="name" type="text" name="cat[name]" value="<%= cat.name %>">
  
  <br>
  
  <label for="birth_date">Birth Date</label>
  <input id="birth_date" type="date" name="cat[birth_date]" value= <%= cat.birth_date %>>
  
  <br>
  
  <label for="color">-- Select a Color --</label>
  <select id= 'color' name="cat[color]">
    <% if action == :new %>
      <option disabled selected>option</option>
    <% end %>
    
    <option <%= cat.color == 'Black' ? 'selected' : '' %> value="Black">Black</option>
    <option <%= cat.color == 'Orange' ? 'selected' : '' %> value="Orange">Orange</option>
    <option <%= cat.color == 'Grey' ? 'selected' : '' %> value="Grey">Grey</option>
    <option <%= cat.color == 'White' ? 'selected' : '' %> value="White">White</option>
    <option <%= cat.color == 'Yellow' ? 'selected' : '' %> value="Yellow">Yellow</option>
    <option <%= cat.color == 'Brown' ? 'selected' : '' %> value="Brown">Brown</option>
  </select>
  
  <br>
  <div>
    <label >Sex</label>
    <input id= 'sex' type="radio" name="cat[sex]" value= 'M' <%= cat.sex == "M" ? 'checked' : '' %>>
    <label for="sex">Male</label>
    <input id= 'sex' type="radio" name="cat[sex]" value= 'F' <%= cat.sex == "F" ? 'checked' : '' %>>
    <label for="sex">Female</label>
  </div>
  <!-- <select id= 'sex' name="cat[sex]">
    <option disabled selected>option</option>
    <option value="M">M</option>
    <option value="F">F</option>
  </select> -->
  
  <br>
  <br>
  
  <label for="description">Description</label>
  <textarea id="description" name="cat[description]"></textarea>
  <br>
  <br>
  <input type="submit" value= <%= final_str %>>
</form>

Cat99/app/views/cats/edit.html.erb
<%= render 'forms', cat: @cat, action: :edit %>

Cat99/app/views/cats/index.html.erb
<h1>ALL deez Cats</h1>

<% @cats.each do |cat|  %>
<ul>
  <li> <%=render 'cat_template', cat: cat, action: :index %> </li>
</ul>
<% end  %>

Cat99/app/views/cats/new.html.erb
<%= render 'forms', cat: @cat, action: :new %>

Cat99/app/views/cats/show.html.erb
<%=render 'cat_template', cat: @cat, action: :show  %>

Cat99/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cat99</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>